baseURL = "https://zvenyach.com/"
languageCode = "en-us"
title = "Zvenyach LLC"

[params]
  description = "Zvenyach LLC: Helping businesses and government work smarter, together."
  images = ["/images/Zvenyach-Logo.png"]
  title = "Zvenyach LLC's website"

[taxonomies]
  series = "series"

copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
[author]
      name = "V. David Zvenyach"
